[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cyclone-intensity"
version = "0.1.0"
description = "Tropical Cyclone Intensity Estimation from Satellite Imagery"
authors = [{ name = "cycml team" }]
dependencies = [
    "torch",
    "torchvision",
    "h5py",
    "pandas",
    "numpy",
    "pyyaml",
    "scikit-learn",
    "matplotlib",
    "seaborn",
    "gdown",
    "tqdm",
    "scipy",
]
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

